FROM ubuntu:18.04

# Tools installed in this docker image:
# bedGraphToBigWig
# bedops       2.4.37     conda:python3
# bedSort
# bedtools     2.25.0
# bowtie2      2.2.6
# bwa          0.7.12
# cutadapt     1.18       conda:python3
# fastqc       0.11.8
# genrich      0.6
# homer 			 4.11       conda:python3
# idr          2.0.4.2    conda:python3
# jre          1.8.0_222
# meme				 5.1.0          
# macs2        2.2.5      conda:python3
# miniconda3   4.7.12.1
# multiqc      1.8        conda:python3
# picardcloud
# samtools     0.1.19

RUN mkdir -p /data2
RUN mkdir -p /opt2
ENV     TZ=America/New_York
RUN     ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Need to add cloud repo to install R v3.6 on ubuntu v16.04
# else default is R v3.2.3 which does not have required libraries like RCurl
RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y libxml2-dev software-properties-common apt-transport-https
#RUN echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/" >> /etc/apt/sources.list
# RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -s -c) main"
#RUN apt-get update && \
#    apt-get upgrade -y --allow-unauthenticated

RUN apt-get install -y cpanminus unzip

RUN cpanm FindBin Term::ReadLine

RUN apt-get install -y \
    bc \
    bedtools \
    bowtie2 \
    bwa \
    cmake \
    default-jre \
    g++ \
    gcc \
    libbz2-dev \
    libcurl4-openssl-dev \
    liblzma-dev \
    libssl-dev \
    make \
    pandoc \
    parallel \
    pigz \
    pkg-config \
    samtools \
    wget \
    zlib1g-dev

# INSTALL R packages

RUN apt-get install -y --allow-unauthenticated r-base-core
COPY install_R_packages.R /opt2
WORKDIR /opt2
RUN Rscript install_R_packages.R

# INSTALL ChIPseeker
COPY install_R_packages_chipseeker.R /opt2
WORKDIR /opt2
RUN Rscript install_R_packages_chipseeker.R

