FROM ubuntu:18.04
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y build-essential python2.7-dev python-numpy python-matplotlib python-pysam python-htseq

RUN mkdir -p /opt2 && mkdir -p /data2

WORKDIR /data2

MAINTAINER vishal.koparde@nih.gov
