FROM nciccbr/ccbr_ubuntu_base_20.04:v2.0
ENV TAG="v1.0"

# Minimap2
WORKDIR /opt2
RUN git clone https://github.com/lh3/minimap2 && cd minimap2 && make
ENV PATH="/opt2/minimap2:$PATH"

# isoCirc
WORKDIR /opt2
RUN ln -s /usr/bin/pip3 /usr/bin/pip3.8 && pip3 install isocirc 

# cleanup etc
COPY Dockerfile.${TAG} /opt2/Dockerfile.${TAG}
RUN if [ -f /opt2/Dockerfile ];then rm -f /opt2/Dockerfile;fi && \
    ln -s Dockerfile.${TAG} Dockerfile && \
    chmod a+r /opt2/Dockerfile.${TAG}
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# details
LABEL maintainer="vishal.koparde@nih.gov"
LABEL github_handle="kopardev"
ARG BUILD_DATE
LABEL build_date=$BUILD_DATE
