BiocManager::install("karyoploteR",update=TRUE,ask=FALSE,dependencies=TRUE)
BiocManager::install("TxDb.Mmusculus.UCSC.mm10.knownGene",update=TRUE,ask=FALSE,dependencies=TRUE)
BiocManager::install("org.Mm.eg.db",update=TRUE,ask=FALSE,dependencies=TRUE)
BiocManager::install("clusterProfiler",update=TRUE,ask=FALSE,dependencies=TRUE)
BiocManager::install("msigdb",update=TRUE,ask=FALSE,dependencies=TRUE)
