FROM nciccbr/ccbr_ubuntu_base_20.04:v3.1
# starting with new v3.1 as base image of ubuntu LTS

# adding extra libraries needed by R packages
RUN apt-get update \
	&& apt-get -y upgrade \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y \
		software-properties-common \
		dirmngr gnupg apt-transport-https \
		ca-certificates \
		libcurl4-openssl-dev \
		libssl-dev \
		libboost-dev \
		libxml2-dev \
		libharfbuzz-dev \
		libfribidi-dev \
		libmagick++-dev \
		libgit2-dev \
		libudunits2-dev

# adding R v 4.3.0
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 \
	&& add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get -y install r-base r-base-dev r-recommended r-base-dev

# Save Dockerfile in the docker
ADD Dockerfile_baser.230602 /opt2/ccbr_baser.dockerfile

WORKDIR /data2
RUN apt-get clean