FROM ubuntu:16.04

RUN mkdir -p /data
RUN mkdir -p /opt

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y cpanminus

RUN apt-get install -y zlibc zlib1g zlib1g-dev make gcc g++ wget
RUN apt-get install -y bowtie2
RUN apt-get install -y build-essential libgtk2.0-dev gtk2.0

RUN cpanm ExtUtils::PkgConfig
RUN cpanm GD 

COPY fastq_screen_v0.13.0.tar.gz /opt
COPY Dockerfile /opt


WORKDIR /data

RUN apt-get clean

MAINTAINER vishal.koparde@nih.gov
