# ccbr_build_rnaseq Dockerfile (v0.0.1)
FROM ubuntu:18.04

MAINTAINER <vishal.koparde@nih.gov>, <kuhnsa@nih.gov>

RUN mkdir -p /data2
RUN mkdir -p /opt2/ucsc/

# Update apt-get before downloading packages
RUN apt-get update && \
    apt-get upgrade -y

# Install dependencies: python (2.7), python (3.6) and pip3, wget to download UCSC binaries
# samtools to install libkrb5.so.3: open shared object file (needed bby UCSC tools)
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes \
	wget \
	python \
	bedtools \
	samtools \
	python3 \
	python3-pip \
	locales && \
apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /opt2/ucsc

# Get a controlled release of UCSC tool from my mirror: https://github.com/skchronicles/ucsc_mirror/
RUN wget https://github.com/skchronicles/ucsc_mirror/raw/main/bedSort && \
	wget https://github.com/skchronicles/ucsc_mirror/raw/main/genePredToBed && \
	wget https://github.com/skchronicles/ucsc_mirror/raw/main/gtfToGenePred && \
	chmod a+rx /opt2/ucsc/*

# Pip install required Python dependencies
## argparse
## Bio
## HTSeq
## numpy
## scipy
## pysam
RUN pip3 install --upgrade pip
RUN pip3 install bio==0.4.1 biopython==1.78 certifi==2020.12.5 chardet==4.0.0 HTSeq==0.13.5 idna==2.10 numpy==1.19.5 pysam==0.16.0.1 requests==2.25.1 scipy==1.5.4 urllib3==1.26.4

# Set environment variable(s)
# Configure "locale", see https://github.com/rocker-org/rocker/issues/19
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen en_US.utf8 \
    && /usr/sbin/update-locale LANG=en_US.UTF-8

# Add UCSC tools to PATH
ENV PATH="/opt2/ucsc":$PATH

COPY Dockerfile /opt2/
WORKDIR /data2
