FROM nciccbr/ccbr_atacseq:v1.1
ENV TAG="v1.2"

# install fastqc
ADD https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip /opt2/
WORKDIR /opt2
RUN unzip fastqc_v0.11.9.zip
WORKDIR /opt2/FastQC
RUN chmod 755 fastqc
RUN ln -s /opt2/FastQC/fastqc /usr/local/bin/fastqc

# SCRIPTS AND DB files

COPY Dockerfile.$TAG /opt2
RUN chmod a+r /opt2/Dockerfile.$TAG

WORKDIR /data2
RUN apt-get clean
