FROM nciccbr/ccbr_atacseq:v1.2
ENV TAG="v1.3"

# install macs2
RUN pip install MACS2

# install ChIPseeker etc
WORKDIR /opt2
COPY install_packages_v1.3.R /opt2
RUN Rscript install_packages_v1.3.R

# SCRIPTS AND DB files

COPY Dockerfile.$TAG /opt2
RUN chmod a+r /opt2/Dockerfile.$TAG

WORKDIR /data2
RUN apt-get clean
