FROM nciccbr/ccbr_atacseq:v1.7
ENV TAG="v1.8"

# install multiqc
RUN pip install multiqc==1.10.1

# SCRIPTS AND DB files

COPY Dockerfile.$TAG /opt2
RUN chmod a+r /opt2/Dockerfile.$TAG

WORKDIR /data2
RUN apt-get clean
