FROM nciccbr/ccbr_atacseq:v1.3
ENV TAG="v1.3.1"

# install pandas
RUN pip install pandas

# SCRIPTS AND DB files

COPY Dockerfile.$TAG /opt2
RUN chmod a+r /opt2/Dockerfile.$TAG

WORKDIR /data2
RUN apt-get clean
