FROM ubuntu:16.04

RUN mkdir -p /d
RUN mkdir -p /opt

RUN apt-get update && \
    apt-get upgrade -y

RUN rm -f /etc/apt/sources.list.d/webupd8team-java.list

RUN apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections 

RUN apt-get install -y default-jre


WORKDIR /data

RUN apt-get clean

MAINTAINER vishal.koparde@nih.gov
