install.packages("plotly", repos="http://cran.us.r-project.org")
install.packages("RColorBrewer", repos="http://cran.us.r-project.org")
install.packages("reshape2", repos="http://cran.us.r-project.org")
install.packages("rmarkdown", repos="http://cran.us.r-project.org")
install.packages("BiocManager", repos="http://cran.us.r-project.org")
install.packages("argparse", repos="http://cran.us.r-project.org")
install.packages("dplyr", repos="http://cran.us.r-project.org")
