#!/bin/bash
dt=$(date +"%d%m%y%H%M%S")
tag="v1.0"
docker build \
    --build-arg BUILD_DATE=${dt} \
    --build-arg TAG=${tag} \
    -f Dockerfile.${tag} \
    -t nciccbr/ccbr_debian_base:${tag} \
    . | \
    tee Dockerfile.${tag}.build.${dt}.log