FROM ubuntu:20.04
LABEL maintainer "Vishal Koparde *(kopardev on GitHub)*"
LABEL github_handle="kopardev"
ARG TAG
ENV TAG="$TAG"
ARG BUILD_DATE
LABEL build_date="$BUILD_DATE"

RUN mkdir -p /opt2 && mkdir -p /data2
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update
# Set the locale
RUN apt-get install -y --no-install-recommends locales && \
	localedef -i en_US -f UTF-8 en_US.UTF-8

RUN apt-get install -y --no-install-recommends \
	bcftools \
	bedops \
	bedtools \
	bowtie \
	bowtie2 \
	build-essential \
	bwa \
	bzip2 \
	curl \
	cmake \
	cpanminus \
	figlet \
	g++ \
	gcc \
	gfortran \
	git \
	libatlas-base-dev \
	libblas-dev \
	libboost-dev \
	libbz2-dev \
	libcurl4-openssl-dev \
	libexpat1-dev \
	libfreetype6-dev \
	libgd-dev \
	libgd-perl \
	libgs-dev \
	libgsl-dev \
	libgsl0-dev \
	libhtml-template-compiled-perl \
	libicu-dev \
	libjudy-dev \
	liblapack-dev \
	liblzma-dev \
	libmysqlclient-dev \
	libncurses-dev \
	libopenmpi-dev \
	libpng-dev \
	librtmp-dev \
	libssl-dev \
	libtool \
	libxml-libxml-debugging-perl \
	libxml-opml-simplegen-perl \
	libxml2-dev \
	libxslt-dev \
	make \
	manpages-dev \
	openjdk-8-jdk \
	parallel \
	pigz \
	python2.7 \
	python3-pip \
	rsync \
	unzip \
	vcftools \
	wget \
	zlib1g \
	zlib1g-dev \
	zlibc && \
	cpanm FindBin Term::ReadLine

#fix python
RUN ln -s /usr/bin/python3.8 /usr/bin/python \
	&& ln -s /usr/bin/python2.7 /usr/bin/python2

# install samtools (newer version)
WORKDIR /opt2
ADD https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2 /opt2/htslib-1.17.tar.bz2
RUN tar xjfv htslib-1.17.tar.bz2 && rm -f htslib-1.17.tar.bz2 && mkdir -p /opt2/htslib
WORKDIR /opt2/htslib-1.17
RUN ./configure --prefix=/opt2/htslib && make && make install 
WORKDIR /opt2
RUN rm -rf /opt2/htslib-1.17
ENV PATH="/opt2/htslib/bin:$PATH"

ADD https://github.com/samtools/samtools/releases/download/1.17/samtools-1.17.tar.bz2 samtools-1.17.tar.bz2
RUN tar xjfv samtools-1.17.tar.bz2 && rm -f samtools-1.17.tar.bz2 && mkdir -p /opt2/samtools
WORKDIR /opt2/samtools-1.17
RUN ./configure --prefix=/opt2/samtools && make && make install 
WORKDIR /opt2
RUN rm -rf /opt2/samtools-1.17
ENV PATH="/opt2/samtools/bin:$PATH"

ADD https://github.com/bcftools/bcftools/releases/download/1.17/bcftools-1.17.tar.bz2 /opt2/bcftools-1.17.tar.bz2
RUN tar xjfv bcftools-1.17.tar.bz2 && rm -f bcftools-1.17.tar.bz2 && mkdir -p /opt2/bcftools
WORKDIR /opt2/bcftools-1.17
RUN ./configure --prefix=/opt2/bcftools && make && make install 
WORKDIR /opt2
RUN rm -rf /opt2/bcftools-1.17
ENV PATH="/opt2/bcftools/bin:$PATH"


RUN python3 -m pip install --upgrade pip && \
	pip3 install --upgrade pip && \
	pip3 install numpy && \
	pip3 install scipy && \
	pip3 install argparse && \
	pip3 install pysam

# cleanup etc
COPY Dockerfile.$TAG /opt2/Dockerfile.baseimage
COPY argparse.bash /opt2
RUN chmod a+rX /opt2/Dockerfile.baseimage && chmod -R a+rx /opt2/argparse.bash
ENV PATH="/opt2/:$PATH"
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
