FROM ubuntu:20.04
LABEL maintainer "Vishal Koparde *(kopardev on GitHub)*"
ENV TAG="v2.0"

RUN mkdir -p /opt2 && mkdir -p /data2
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update
# perl fixes
RUN apt-get install -y cpanminus build-essential gfortran make gcc g++ cmake 
RUN cpanm FindBin Term::ReadLine
# Set the locale
RUN apt-get install -y locales && localedef -i en_US -f UTF-8 en_US.UTF-8
# RUN apt-get install -y zlib1g-dev libncurses-dev libbz2-dev liblzma-dev libxml2-dev libssl-dev libexpat1-dev libgd-dev
RUN apt-get install -y librtmp-dev libssl-dev libatlas-base-dev libblas-dev libboost-dev libbz2-dev \
 libexpat1-dev libfreetype6-dev libgd-dev libgd-perl libgs-dev libgsl-dev libgsl0-dev \
 libhtml-template-compiled-perl libicu-dev libjudy-dev liblapack-dev liblzma-dev libmysqlclient-dev libncurses-dev \
 libopenmpi-dev libpng-dev libssl-dev libtool libxml-libxml-debugging-perl libxml-opml-simplegen-perl \
 libxml2-dev libxslt-dev manpages-dev zlib1g-dev libcurl4-openssl-dev
RUN apt-get install -y unzip zlibc zlib1g bzip2 wget git curl pigz parallel


#install pip
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip && \
	pip3 install numpy && \
	pip3 install scipy && \
	pip3 install argparse && \
	pip3 install pysam

#install other bioinformatics tools
RUN apt-get install -y bowtie bowtie2 bwa bedtools bedops samtools bcftools vcftools  

#install R
RUN apt-get install -y r-base r-base-dev r-base-core

#install java
RUN apt-get install -y openjdk-8-jdk

#install figlet
RUN apt-get install -y figlet

#fix python
RUN ln -s /usr/bin/python3.8 /usr/bin/python

#add python2/rsync
RUN apt-get install -y python2.7 rsync && ln -s /usr/bin/python2.7 /usr/bin/python2

# install samtools (newer version)
WORKDIR /opt2
COPY samtools-1.15.1.tar.bz2 .
RUN tar xjfv samtools-1.15.1.tar.bz2 && rm -f samtools-1.15.1.tar.bz2 && mkdir -p /opt2/samtools
WORKDIR /opt2/samtools-1.15.1
RUN ./configure --prefix=/opt2/samtools && make && make install 
WORKDIR /opt2
RUN rm -rf /opt2/samtools-1.15.1
ENV PATH="/opt2/samtools/bin:$PATH"

# cleanup etc
COPY Dockerfile.$TAG /opt2/Dockerfile.baseimage
COPY argparse.bash /opt2
COPY printversions.bash /opt2/printversions
RUN chmod a+rX /opt2/Dockerfile.baseimage && chmod -R a+rx /opt2/argparse.bash && chmod -R a+rx /opt2/printversions.bash
ENV PATH="/opt2/:$PATH"
WORKDIR /data2
RUN apt-get clean && rm -rf /var/lib/apt/lists/*