#!/usr/bin/env bash

if [ "$#" != "1" ];then
    echo "Provide a TAG as argument!"
    exit
fi
tag="$1"

# set variables
SCRIPTNAME="$0"
SCRIPTDIRNAME=$(readlink -f $(dirname "$SCRIPTNAME"))

${SCRIPTDIRNAME}/build $tag && ${SCRIPTDIRNAME}/push $tag