#!/bin/bash

if [ "$#" != "1" ];then
    echo "Provide a TAG as argument!"
    exit
fi

dockerhub_account="nciccbr"
# foldername is the reponame
CWD=`pwd`
JUSTFOLDERNAME=$(basename $CWD)
reponame="$JUSTFOLDERNAME"

dt=$(date +"%y%m%d")
tag="$1"

docker push ${dockerhub_account}/${reponame}:${tag}
docker tag ${dockerhub_account}/${reponame}:${tag} ${dockerhub_account}/${reponame}:latest
docker push ${dockerhub_account}/${reponame}:latest
