FROM 		ubuntu:16.04
MAINTAINER 	vishal.koparde@nih.gov


RUN 		mkdir -p /data \
&&			mkdir -p /opt

RUN			apt-get update \
&&			apt-get upgrade -y 

RUN 		apt-get install -y zlibc zlib1g zlib1g-dev make gcc g++ wget \
			r-base-core libboost-dev \
			libncurses-dev libbz2-dev liblzma-dev \
			bowtie bowtie2 \
			pigz bzip2 \
			python3 python3-pip

RUN 		pip3 install --upgrade pip
RUN			pip3 install numpy RSeQC

WORKDIR /opt
COPY 2.7.0f.tar.gz /opt
RUN tar -xzf 2.7.0f.tar.gz
WORKDIR /opt/STAR-2.7.0f/source
RUN make STAR
ENV PATH="/opt/STAR-2.7.0f/source":$PATH

WORKDIR /opt
COPY v1.3.1.tar.gz /opt
RUN tar -xzf v1.3.1.tar.gz
WORKDIR /opt/RSEM-1.3.1
RUN make && make ebseq
ENV PATH="/opt/RSEM-1.3.1":$PATH

WORKDIR /data
COPY Dockerfile.v0.0.1 /opt
RUN apt-get clean

