FROM nciccbr/ccbr_ubuntu_base_20.04:v5

# build time variables
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}

# install rseqc
RUN pip3 install --upgrade pip
RUN pip3 install numpy RSeQC

# install star
WORKDIR /opt2
ADD https://github.com/alexdobin/STAR/archive/refs/tags/2.7.0f.tar.gz /opt2
RUN tar -xzvf 2.7.0f.tar.gz
WORKDIR /opt2/STAR-2.7.0f/source
RUN make STAR
ENV PATH="/opt2/STAR-2.7.0f/source":$PATH

# install rsem
WORKDIR /opt2
ADD https://github.com/deweylab/RSEM/archive/refs/tags/v1.3.1.tar.gz /opt2
RUN tar -xzvf v1.3.1.tar.gz
WORKDIR /opt2/RSEM-1.3.1
RUN make && make ebseq
ENV PATH="/opt2/RSEM-1.3.1":$PATH

# install cufflinks
WORKDIR /opt2
ADD http://cole-trapnell-lab.github.io/cufflinks/assets/downloads/cufflinks-2.2.1.Linux_x86_64.tar.gz /opt2
RUN tar -xzvf cufflinks-2.2.1.Linux_x86_64.tar.gz && rm -f *.tar.gz
ADD https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred /opt2/cufflinks-2.2.1.Linux_x86_64
RUN chmod a+x /opt2/cufflinks-2.2.1.Linux_x86_64/gtfToGenePred
ENV PATH="/opt2/cufflinks-2.2.1.Linux_x86_64":$PATH

# cleanup etc
# Save Dockerfile in the docker
COPY Dockerfile /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/
WORKDIR /data2


