FROM nciccbr/ccbr_ubuntu_base_20.04:v1.4

RUN apt-get install -y libffi-dev libdeflate-dev libsqlite3-dev

# According to https://github.com/nedialkova-lab/mim-tRNAseq/issues/33#issuecomment-1168411432
# mimseq may work best with python/3.7
# python3.8 gave error described in https://github.com/nedialkova-lab/mim-tRNAseq/issues/33
# default version is 3.8 hence install 3.7 and setting that as default
# distutils dev packages are required to run pip and install packages via pip for python3.7
# Build python 3.8 from source
WORKDIR /opt2
RUN wget https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz && \
	tar -xvf Python-3.7.1.tgz && \
	rm Python-3.7.1.tgz
WORKDIR /opt2/Python-3.7.1/ 
RUN ./configure --enable-loadable-sqlite-extensions --enable-optimizations && \
  make && \
  make altinstall

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1 && \
  update-alternatives --install /usr/bin/python python /usr/local/bin/python3.7 2 && \
  update-alternatives --set python /usr/local/bin/python3.7 && \
  python -m pip install --upgrade pip

RUN python -m pip install numpy==1.21.1
RUN python -m pip install pandas==1.3.1
RUN python -m pip install Biopython==1.79
RUN python -m pip install pyfiglet==0.8.post1
RUN python -m pip install pysam==0.16.0.1
RUN python -m pip install seaborn==0.11.1
RUN python -m pip install pybedtools==0.8.2
RUN python -m pip install requests==2.26.0

WORKDIR /opt2
RUN git clone https://github.com/nedialkova-lab/mim-tRNAseq.git && \
  cd mim-tRNAseq && \
  python setup.py build && \
  python setup.py install
