install.packages("devtools")
install.packages("RColorBrewer")
install.packages("pheatmap")
install.packages("calibrate")
install.packages("gridExtra")
install.packages("plyr")
install.packages("dplyr")
install.packages("reshape2")
install.packages("circlize")
install.packages("tidyversion")
install.packages("ggplot2")
install.packages("ggpol")
install.packages("BiocManager")
BiocManager::install("DESeq2",update=TRUE,ask=FALSE)
BiocManager::install("ComplexHeatmap", update=TRUE, ask=FALSE)
